package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"filippo.io/age"
	"github.com/spf13/cobra"
)

var keygenOutput string

var keygenCmd = &cobra.Command{
	Use:   "keygen",
	Short: "Generate a new Age X25519 keypair",
	Long:  "Generates a new Age X25519 keypair. By default, appends the private key to ~/.envvault/keys.txt and prints the public key to stdout.",
	RunE: func(cmd *cobra.Command, args []string) error {
		// 1. Generate the identity
		identity, err := age.GenerateX25519Identity()
		if err != nil {
			return fmt.Errorf("generating keypair: %w", err)
		}

		publicKey := identity.Recipient().String()
		privateKey := identity.String()

		// 2. Determine output path
		outPath := keygenOutput
		if outPath == "" {
			home, err := os.UserHomeDir()
			if err != nil {
				return fmt.Errorf("finding home directory: %w", err)
			}
			outPath = filepath.Join(home, ".envvault", "keys.txt")
		}

		// 3. Ensure directory exists
		if err := os.MkdirAll(filepath.Dir(outPath), 0700); err != nil {
			return fmt.Errorf("creating directory: %w", err)
		}

		// 4. Open file in append mode (allows users to have multiple keys)
		f, err := os.OpenFile(outPath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0600)
		if err != nil {
			return fmt.Errorf("opening key file: %w", err)
		}
		defer f.Close()

		// 5. Write private key with a helpful comment
		if _, err := fmt.Fprintf(f, "# generated by envvault\n%s\n", privateKey); err != nil {
			return fmt.Errorf("writing private key: %w", err)
		}

		// 6. Output results
		fmt.Printf("🔑 Keypair generated!\n")
		fmt.Printf("Public key:  %s\n", publicKey)
		fmt.Printf("Private key: saved to %s (keep this secret!)\n", outPath)

		return nil
	},
}

func init() {
	keygenCmd.Flags().StringVarP(&keygenOutput, "output", "o", "", "Save private key to a specific file (defaults to ~/.envvault/keys.txt)")
	rootCmd.AddCommand(keygenCmd)
}
